smbc-digital/flooding-service

.vscode/launch.json, .vscode/tasks.json, src/Config/appsettings.json, src/Constants/ConfirmConstants.cs, src/Controllers/HomeController.cs, src/Controllers/Models/FloodingRequest.cs, src/Mappers/ConfirmIntegrationFormOptionsMapper.cs, src/Mappers/FloodingRequestMapper.cs, src/Models/ConfirmAttributeFormOptions.cs, src/Models/PavementVerintOptions.cs, src/Services/FloodingService.cs, src/Startup.cs, src/Utils/ServiceCollectionExtensions/ServiceCollectionExtensions.cs, src/flooding-service.csproj, tests/Controller/HomeControllerTests.cs, tests/Mappers/ConfirmIntegrationFormOptionsMapperTests.cs, tests/Mappers/FloodingRequestMapperTests.cs, tests/Services/FloodingServiceTests.cs
Add the necessary methods to complete the pavement journey
=> feat(Pavement journey): add controller, service, mappers, unit tests

src/Controllers/HomeController.cs, tests/Controller/HomeControllerTests.cs
=> chore(Controller): add logging to debug

src/Controllers/HomeController.cs, tests/Controller/HomeControllerTests.cs
=> chore(Controller): fix logger

src/Mappers/FloodingRequestMapper.cs
=> fix(Mapper): set both EventCode and EventId

src/Mappers/ConfirmIntegrationFormOptionsMapper.cs, src/Mappers/FloodingRequestMapper.cs
=> fix(Mapper): add eventcode to ConfirmMapper

tests/Mappers/ConfirmIntegrationFormOptionsMapperTests.cs
=> fix(Tests)

src/Config/appsettings.json, src/Mappers/ConfirmIntegrationFormOptionsMapper.cs, src/Models/ConfirmAttributeFormOptions.cs, tests/Mappers/ConfirmIntegrationFormOptionsMapperTests.cs, tests/Services/FloodingServiceTests.cs
=> fix(config): add ServiceCode, SubjectCode, ClassCode to config

src/Config/appsettings.json
=> chore(appSettings): update confg values

src/Controllers/HomeController.cs, src/Controllers/Models/FloodingRequest.cs, src/Services/FloodingService.cs, src/Utils/HealthChecks/HealthCheckOptions.cs, tests/Services/FloodingServiceTests.cs
=> chore(FloodingService): add logger for debugging

src/Services/FloodingService.cs, tests/Services/FloodingServiceTests.cs
=> chore(FloodingService): add HttpClient

src/Services/FloodingService.cs, tests/Services/FloodingServiceTests.cs
=> fix(FloodingServiceTests): skip unit tests

src/Services/FloodingService.cs, tests/Helpers/MailHelperTests.cs, tests/Services/FloodingServiceTests.cs
=> chore(FloodingService): comment out call to ConvertLatLng

src/Helpers/MailHelper.cs, src/Services/FloodingService.cs, tests/Helpers/MailHelperTests.cs, tests/Services/FloodingServiceTests.cs
=> chore(MailHelper): add check for emailAddress

src/Config/appsettings.json, src/Extensions/StringExtensions.cs, src/Helpers/MailHelper.cs, src/flooding-service.csproj
=> chore(private land journey): add privateLand case to StringExtensions, add privateLand case to MailHelper

src/Helpers/MailHelper.cs, tests/Helpers/MailHelperTests.cs
=> fix(MailHelper): fix selecting template for highWaterLevels journey

src/Config/appsettings.json
=> chore(appsettings): amend title for private land journey

src/Config/appsettings.json, src/Controllers/Models/FloodingRequest.cs, src/Extensions/StringExtensions.cs, src/Helpers/MailHelper.cs, src/Helpers/StreetHelper.cs, src/Mappers/ConfirmIntegrationFormOptionsMapper.cs, src/Mappers/FloodingRequestMapper.cs, src/Models/FloodingConfiguration.cs, src/Services/FloodingService.cs, src/flooding-service.csproj, tests/Helpers/MailHelperTests.cs, tests/Mappers/ConfirmIntegrationFormOptionsMapperTests.cs, tests/Mappers/FloodingRequestMapperTests.cs, tests/flooding-service-tests.csproj
Added logic to handle the home flooding journey
=> feat: home journey

src/Mappers/FloodingRequestMapper.cs
Prepopulate location with 'Where is the flood'
=> fix (location): prepopulate location for where is the flood

src/Config/appsettings.json, src/Mappers/FloodingRequestMapper.cs, src/Models/VerintOptions.cs, src/Services/FloodingService.cs, tests/Mappers/FloodingRequestMapperTests.cs, tests/Services/FloodingServiceTests.cs
Add human-readable text for flooding location
=> chore (floodinglocation): Add human readable text for flooding location

src/Config/appsettings.json, src/Services/FloodingService.cs
Fixed config name
Add config values for river or stream
Add logic to get correct config
=> fix(appsettings): fix discrepancy in config name and add river or stream option

src/Config/appsettings.json
=> fix(appsettings): fix incorrect config

src/flooding-service.csproj
Update StockportGovUK.Extensions package
=> chore(project): updated StockportGovUK.Extensions package

src/Controllers/Models/FloodingRequest.cs, src/Helpers/StreetHelper.cs, src/Mappers/FloodingRequestMapper.cs, src/Models/Address.cs, src/Services/FloodingService.cs, src/flooding-service.csproj, tests/Mappers/FloodingRequestMapperTests.cs, tests/Services/FloodingServiceTests.cs
Add easting and northing to private property locations
=> feat: add Easting and Northing for private property
